name: project0
# either manually started, or on a schedule
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *' # At 4:00 UTC everyday
jobs:

  install:
    env:
        MAGIC_VERSION:          8.3.209
        PDK_ROOT:               $GITHUB_WORKSPACE/pdk
        OPENLANE_ROOT:          $GITHUB_WORKSPACE/openlane
        SKYWATER_COMMIT:        c094b6e83a4f9298e47f696ec5a7fd53535ec5eb
        OPEN_PDKS_COMMIT:       14db32aa8ba330e88632ff3ad2ff52f4f4dae1ad
        CARAVEL_COMMIT:         5712871d27c08900d18edc72a7f534cc8be1b2dd
        OPENLANE_TAG:           mpw-3a
        OPENLANE_IMAGE_NAME:    efabless/openlane:mpw-3a

    # ubuntu
    runs-on: ubuntu-latest
    steps:

    # checkout the repo to get the scripts
    - uses: actions/checkout@v2

    # dependencies we can install from package manager
    - name: install deps
      run: sudo apt-get install -y tcsh csh tcl-dev tk-dev libcairo2-dev

    # magic dependency
    - name: install magic
      run: bash ${GITHUB_WORKSPACE}/.github/scripts/install_magic.sh

    # test
    - name: test magic
      run: magic --version

    # install the PDK, OpenLane
    - name: install PDK & OpenLane
      run: bash ${GITHUB_WORKSPACE}/.github/scripts/install_pdk.sh

    # build the user project and wrapper
    - name: build GDS
      run: |
        cd caravel_user_project/openlane
        docker run -v $OPENLANE_ROOT:/openLANE_flow -v $PDK_ROOT:$PDK_ROOT -v $PWD/..:/project -v $CARAVEL_ROOT:$CARAVEL_ROOT -e PDK_ROOT=$PDK_ROOT -e CARAVEL_ROOT=$CARAVEL_ROOT -u $(id -u $USER):$(id -g $USER) $OPENLANE_IMAGE_NAME sh -c "cd /project/openlane && flow.tcl -design ./user_proj_example -save_path .. -save -tag user_proj_example -overwrite"
        docker run -v $OPENLANE_ROOT:/openLANE_flow -v $PDK_ROOT:$PDK_ROOT -v $PWD/..:/project -v $CARAVEL_ROOT:$CARAVEL_ROOT -e PDK_ROOT=$PDK_ROOT -e CARAVEL_ROOT=$CARAVEL_ROOT -u $(id -u $USER):$(id -g $USER) $OPENLANE_IMAGE_NAME sh -c "cd /project/openlane && flow.tcl -design ./user_project_wrapper -save_path .. -save -tag user_project_wrapper -overwrite"

    # archive the gds and final report for the user project example
    - name: Archive Proj GDS
      uses: actions/upload-artifact@v2
      with:
          name: Proj GDS
          path: caravel_user_project/gds/user_proj_example.gds

    - name: Archive Proj Signoff
      uses: actions/upload-artifact@v2
      with:
          name: Proj Report
          path: caravel_user_project/openlane/user_proj_example/runs/user_proj_example/reports/final_summary_report.csv

    # archive the gds and final report for the user project wrapper
    - name: Archive Wrapper GDS
      uses: actions/upload-artifact@v2
      with:
          name: Wrapper GDS
          path: caravel_user_project/gds/user_project_wrapper.gds

    - name: Archive Wrapper Signoff
      uses: actions/upload-artifact@v2
      with:
          name: Wrapper Report
          path: caravel_user_project/openlane/user_project_wrapper/runs/user_project_wrapper/reports/final_summary_report.csv
