name: project0
# either manually started, or on a schedule
on: push
jobs:
  install:
    # ubuntu
    runs-on: ubuntu-latest
    steps:

    # magic dependency
    - name: install magic
      run: >
        sudo apt-get install -y tcsh csh tcl-dev tk-dev libcairo2-dev;
        git clone git://opencircuitdesign.com/magic;
        cd magic;
        git checkout 8.3.209;
        ./configure;
        make;
        sudo make install;

    # test
    - name: test magic
      run: magic --version

    - name: caravel_user_project
      run: >
        export PDK_ROOT=$(pwd)/pdk;
        export OPENLANE_ROOT=$(pwd)/openlane;
        export SKYWATER_COMMIT=c094b6e83a4f9298e47f696ec5a7fd53535ec5eb;
        export OPEN_PDKS_COMMIT=14db32aa8ba330e88632ff3ad2ff52f4f4dae1ad;
        export OPENLANE_TAG=mpw-3a;
        export OPENLANE_IMAGE_NAME=efabless/openlane:$OPENLANE_TAG;
        echo $PDK_ROOT;
        echo $OPENLANE_ROOT;
        echo $OPENLANE_IMAGE_NAME;
        git clone https://github.com/efabless/caravel_user_project.git;
        cd caravel_user_project;
        git checkout mpw-3;
        export CARAVEL_ROOT=$(pwd)/caravel;
        make install;
        cd caravel;
        git checkout 5712871d27c08900d18edc72a7f534cc8be1b2dd;
        git log | head;
        cd ..;
        make pdk;
        make openlane;
        cd openlane;
        docker run -v $OPENLANE_ROOT:/openLANE_flow -v $PDK_ROOT:$PDK_ROOT -v $PWD/..:/project -v $CARAVEL_ROOT:$CARAVEL_ROOT -e PDK_ROOT=$PDK_ROOT -e CARAVEL_ROOT=$CARAVEL_ROOT -u $(id -u $USER):$(id -g $USER) $OPENLANE_IMAGE_NAME sh -c "cd /project/openlane && flow.tcl -design ./user_proj_example -save_path .. -save -tag user_proj_example -overwrite";
        docker run -v $OPENLANE_ROOT:/openLANE_flow -v $PDK_ROOT:$PDK_ROOT -v $PWD/..:/project -v $CARAVEL_ROOT:$CARAVEL_ROOT -e PDK_ROOT=$PDK_ROOT -e CARAVEL_ROOT=$CARAVEL_ROOT -u $(id -u $USER):$(id -g $USER) $OPENLANE_IMAGE_NAME sh -c "cd /project/openlane && flow.tcl -design ./user_project_wrapper -save_path .. -save -tag user_project_wrapper -overwrite";

    # archive the gds and final report for the user project example
    - name: Archive Proj GDS
      uses: actions/upload-artifact@v2
      with:
          name: Proj GDS
          path: caravel_user_project/gds/user_proj_example.gds

    - name: Archive Proj Signoff
      uses: actions/upload-artifact@v2
      with:
          name: Proj Report
          path: caravel_user_project/openlane/user_proj_example/runs/user_proj_example/reports/final_summary_report.csv

    # archive the gds and final report for the user project wrapper
    - name: Archive Wrapper GDS
      uses: actions/upload-artifact@v2
      with:
          name: Wrapper GDS
          path: caravel_user_project/gds/user_project_wrapper.gds

    - name: Archive Wrapper Signoff
      uses: actions/upload-artifact@v2
      with:
          name: Wrapper Report
          path: caravel_user_project/openlane/user_project_wrapper/runs/user_project_wrapper/reports/final_summary_report.csv
