name: project0
# either manually started, or on a schedule
on: push
jobs:
  install:
    # ubuntu
    runs-on: ubuntu-latest
    steps:

    # magic dependency
    - name: install magic
      run: >
        sudo apt-get install -y tcsh csh tcl-dev tk-dev libcairo2-dev;
        git clone git://opencircuitdesign.com/magic;
        cd magic;
        git checkout 8.3.209;
        ./configure;
        make;
        sudo make install;

    # test
    - name: test magic
      run: magic --version

    - name: caravel_user_project
      run: >
        export COMPOSE_INTERACTIVE_NO_CLI=1;
        export PDK_ROOT=$(pwd)/pdk;
        export OPENLANE_ROOT=$(pwd)/openlane;
        export SKYWATER_COMMIT=c094b6e83a4f9298e47f696ec5a7fd53535ec5eb;
        export OPEN_PDKS_COMMIT=14db32aa8ba330e88632ff3ad2ff52f4f4dae1ad;
        export OPENLANE_TAG=2021.09.19_20.25.16;
        export OPENLANE_IMAGE_NAME=efabless/openlane:$OPENLANE_TAG;
        echo $PDK_ROOT;
        echo $OPENLANE_ROOT;
        echo $OPENLANE_IMAGE_NAME;
        git clone https://github.com/efabless/caravel_user_project.git;
        cd caravel_user_project;
        git checkout mpw-3;
        export CARAVEL_ROOT=$(pwd)/caravel;
        make install;
        cd caravel;
        git checkout mpw-3;
        git log | head;
        cd ..;
        make pdk;
        make openlane;
        make user_proj_example;

    - name: Archive GDS
      uses: actions/upload-artifact@v2
      with:
          name: GDS
          path: gds/user_project_wrapper.gds
